#!/usr/bin/env python3
"""Build `src/models/project.json` - the MS Project host model.

Project is the one Office host whose model can't be generated by
tools/generate_model.py: that path drives COM through comtypes and needs Windows
with Project installed. This builds the model from Microsoft's published
reference instead, so it runs anywhere.

Without a Project model, Project VBA is unanalysable - a real 1800-line codebase
reported 604 errors and scored 0/100, every one of them a false positive,
because Task.UniqueID and the pj* constants were unknown.

Everything here is GENERATED from two extracted sources, both committed:

  tools/data/project_api.json        103 classes, 2,924 members
  tools/data/project_vba_enums.json  172 enumerations, 4,907 pj* constants

Both are written by tools/extract_project_docs.py from a clone of
MicrosoftDocs/VBA-Docs - the repository the published
learn.microsoft.com/office/vba/api/project.* pages are built from. They are
build inputs, not sources: not committed, same as build_mscomctl_model.py's
refs file. The shipped artifact is src/models/project.json.

Nothing is typed by hand except the OVERRIDES below, each of which says why it
exists. That rule isn't fastidiousness - it's the lesson from the version of
this file that DID type things by hand, which in one afternoon:

  - invented Resource.Generic and Resource.Inactive. Both 404. The real members
    are EnterpriseGeneric and EnterpriseInactive.
  - invented nine pj* constants, pjStandard among them - the one that had
    already cost us a module - plus pjAssignment, pjCalendarScreen, pjMonth.
  - dropped Resource.UniqueID and Assignment.ResourceUniqueID, which then
    showed up as errors against working code.
  - guessed twelve Project members that a probe on a real Project 365 build
    contradicted, including Project.Assignments (Task and Resource have it,
    Project doesn't) and three Default* names that are really
    DefaultDurationUnits / DefaultWorkUnits.

A model is a WHITELIST: a name listed wrongly makes the analyser bless a typo,
which is worse than having no model at all. Generating it removes the one
failure mode careful reading can't.

Generation also sidesteps a documentation bug for free. The project.assignments
OBJECT page carries the Assignment object's member tables by mistake, so reading
it would bless Assignments.Work and Assignments.Text1..30. The extractor reads
member FILES, and Project.Assignments.Work.md doesn't exist. Six members.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "data")
API = os.path.join(DATA, "project_api.json")
ENUMS = os.path.join(DATA, "project_vba_enums.json")
OUT = os.path.join(ROOT, "src", "models", "project.json")

PRIMITIVES = {"String", "Long", "Double", "Integer", "Boolean", "Variant",
              "Date", "Currency", "Byte", "Single", "Object", "Nothing"}

# ---------------------------------------------------------------------------
# The only hand-written part of this file. Each entry is a judgment the data
# can't make for itself.
# ---------------------------------------------------------------------------
ADD_MEMBERS = {
    # Hidden in the type library and documented nowhere - there is no
    # Project.Project.NewTasksAreManual.md - but REAL. Code in the wild assigns
    # to it from an early-bound Project variable, which would not COMPILE if the
    # member didn't exist, never mind run. Reading it raises 438, which is what
    # write-only or hidden looks like from the outside.
    #
    # This single member is why documentation alone isn't enough: docs describe
    # the SUPPORTED API, a type library carries what actually EXISTS.
    ("Project", "NewTasksAreManual"): {"type": "Boolean"},
}

RETYPE = {
    # Documented as plain Object, but it iterates as Resource and real code
    # relies on that. Typed as the collection so member access through it stays
    # checked rather than silently unchecked.
    ("Project", "Resources"): "Resources",
}

# Documented parameter types are NOT carried into the model. The analyser
# defaults an argument with no `mechanism` to ByRef and then strict-compares its
# type against whatever it inferred at the call site; a type typed `Variant`
# short-circuits that check. Since the docs' types are loose (enum names, bare
# "Variant", 135 members with no type at all), claiming them would risk
# rejecting valid code - the failure direction that gets a checker switched off.
# Names and per-position optionality are carried, which is what enables
# named-argument checking without that risk.
ARG_TYPE = "Variant"

RELAX_ARGS = {
    # Documented Required, yet called bare everywhere including Microsoft's own
    # samples. A compile-safety checker that flags working code gets switched
    # off, so these take zero.
    ("Task", "UnlinkPredecessors"),
    ("Task", "UnlinkSuccessors"),
}

# Reachable unqualified. All are Application members; MS sample code uses them
# bare throughout ("ActiveProject.Tasks.Add ...", "Projects.Count").
GLOBALS = {
    "Application": "Application",
    "ActiveProject": "Project",
    "ActiveSelection": "Selection",
    "ActiveCell": "Cell",
    "ActiveWindow": "Window",
    "Projects": "Projects",
}

# VBA/MSForms names missing from src/std_model.json. Not Project-specific, so
# they belong in the standard model - carried here meanwhile so Project code
# using them doesn't report false errors.
STD_GAPS = {
    "UserForms": {"type": "Object"},
    "Load": {"type": "Function", "returns": "Nothing", "min_args": 1, "max_args": 1},
    "Unload": {"type": "Function", "returns": "Nothing", "min_args": 1, "max_args": 1},
    "vbHide": {"type": "Long"},
    "vbNormalFocus": {"type": "Long"},
    "vbMinimizedFocus": {"type": "Long"},
    "vbMaximizedFocus": {"type": "Long"},
    "vbNormalNoFocus": {"type": "Long"},
    "vbMinimizedNoFocus": {"type": "Long"},
}


def load(path, what):
    if not os.path.exists(path):
        sys.exit(f"missing {path}\n"
                 f"  {what}\n\n"
                 f"  git clone --filter=blob:none --no-checkout --depth 1 \\\n"
                 f"      https://github.com/MicrosoftDocs/VBA-Docs.git\n"
                 f"  cd VBA-Docs && git sparse-checkout init --no-cone \\\n"
                 f"      && git sparse-checkout set '/api/project.*' '/project' \\\n"
                 f"      && git checkout && cd ..\n"
                 f"  python tools/extract_project_docs.py VBA-Docs")
    return json.load(open(path))


def main():
    api = load(API, "extract it first:")
    enum_src = load(ENUMS, "extract it first:")
    known = set(api["classes"])

    def maptype(t):
        """A documented type name -> something the analyser can use."""
        if t is None:
            # The page exists but states no type at all - 135 of them, e.g.
            # Application.GetCellInfo. The member is real; its type isn't
            # stated, and Variant is the honest answer rather than a guess.
            return "Variant"
        if t in PRIMITIVES:
            return t
        if t.startswith("Pj"):
            return "Long"                  # every Pj* enumeration is Long-backed
        if t == "DateType":
            # Declared verbatim on a handful of pages, with no definition page
            # anywhere in the reference.
            return "Variant"
        if t in known:
            return t
        # A real type we don't model: its members go unchecked rather than
        # wrongly rejected.
        return "Object"

    classes = {}
    for cls, members in api["classes"].items():
        out = {}
        for nm, spec in members.items():
            plist = spec.get("params") or []
            total = len(plist)
            req = sum(1 for a in plist if not a["optional"])
            if (cls, nm) in RELAX_ARGS:
                req = 0
            rt = RETYPE.get((cls, nm)) or maptype(spec.get("type"))

            if spec["kind"] == "method" or total:
                # Properties take arguments too - Project.BaselineSavedDate
                # does - so assuming zero would reject a valid call.
                entry = {"type": "Function", "returns": rt,
                         "min_args": req, "max_args": total}
                if plist:
                    entry["args"] = [{"name": a["name"], "type": ARG_TYPE,
                                      "is_optional": a["optional"]}
                                     for a in plist]
                out[nm] = entry
            else:
                out[nm] = {"type": rt}
        classes[cls] = {"type": cls, "members": out}

    for (cls, nm), spec in ADD_MEMBERS.items():
        classes.setdefault(cls, {"type": cls, "members": {}})["members"][nm] = spec

    globals_ = {nm: {"type": t if t in classes else "Object"}
                for nm, t in GLOBALS.items()}
    globals_.update(STD_GAPS)

    enums, pj = {}, 0
    for enum_name, body in enum_src.items():
        members = body.get("members", {})
        enums[enum_name] = dict(members)
        for const in members:
            globals_[const] = {"type": "Long"}
            pj += 1

    model = {"globals": globals_, "classes": classes, "enums": enums}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        json.dump(model, fh, indent=1, sort_keys=True)
        fh.write("\n")

    total = sum(len(c["members"]) for c in classes.values())
    print(f"wrote {OUT}")
    print(f"  {len(classes)} classes, {total} members")
    print(f"  {len(globals_)} globals ({pj} pj* constants from {len(enums)} enums)")
    print(f"  hand-written: {len(ADD_MEMBERS)} added, {len(RETYPE)} retyped, "
          f"{len(RELAX_ARGS)} arg-relaxed")
    for c in ("Application", "Project", "Task", "Resource", "Assignment",
              "Tasks", "Resources", "Assignments", "EventInfo"):
        if c in classes:
            print(f"    {c:12} {len(classes[c]['members']):4}")


if __name__ == "__main__":
    main()
